"""Add ICE, IF, and business info fields to teams table

Revision ID: 06464ac3b19f
Revises: ffe2133c324b
Create Date: 2025-07-03 18:07:32.207281

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '06464ac3b19f'
down_revision = 'ffe2133c324b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ice', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('if_number', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('address', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(), nullable=True))
        batch_op.drop_column('stripe_customer_id')
        batch_op.drop_column('current_period_start')
        batch_op.drop_column('monthly_reset_date')
        batch_op.drop_column('subscription_status')
        batch_op.drop_column('trial_end')
        batch_op.drop_column('monthly_invoice_count')
        batch_op.drop_column('stripe_subscription_id')
        batch_op.drop_column('subscription_plan')
        batch_op.drop_column('current_period_end')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_period_end', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('subscription_plan', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('stripe_subscription_id', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('monthly_invoice_count', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('trial_end', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('subscription_status', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('monthly_reset_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('current_period_start', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('stripe_customer_id', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_column('email')
        batch_op.drop_column('phone')
        batch_op.drop_column('address')
        batch_op.drop_column('if_number')
        batch_op.drop_column('ice')

    # ### end Alembic commands ###
