"""Add CNIE and professional tax number fields to teams table

Revision ID: 9f8e7d6c5b4a
Revises: 7f8e9d1a2b3c
Create Date: 2025-01-19 17:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f8e7d6c5b4a'
down_revision = '7f8e9d1a2b3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cnie', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('professional_tax_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_column('professional_tax_number')
        batch_op.drop_column('cnie')
    # ### end Alembic commands ### 